title: Ciara Germany
# logo: /assets/img/logo.png
description: Data chaos? Not a problem. My specialty is delivering crystal-clear insights—even with a hearing aid.
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
